### ISSUE TITLE
Why is your Faceswapper project page mis-named "Faceswap" rather than "Faceswapper"?

### ISSUE THREAD

**Issue by gessyoo** [andy6804tw/faceswapper#5]
The name "Faceswap" on your page, https://github.com/andy6804tw/faceswapper is confusing users seeking support for your project.  There is already an existing github project called "Faceswap."  To avoid confusing your users and public visitors, you should clearly identify your project as "Faceswapper" on the project landing page.

**Comment by andy6804tw** [comment]
@gessyoo Thank you for your suggestion. I appreciate your feedback regarding the confusion caused by the name "Faceswap" on my page. I will make the necessary changes and clearly identify my project as "Faceswapper" on the project landing page. Thank you again for bringing this to my attention.
